Use v0.1.11, the code expect this version.
I got this error from the microservices process:
Error: The pgvecto.rs extension version is 0.1.13 instead of the expected version 0.1.11.
If you're using the 'latest' tag, please switch to 'tensorchord/pgvecto-rs:pg15-v0.1.11'.